### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by uriva** [tennashi/deno-diff-parser#1]
```
TypeError: Cannot read properties of undefined (reading 'hunks')
    at https://deno.land/x/diff_parser@v0.2.0/diff.ts:88:31
    at Array.forEach (<anonymous>)
    at parse (https://deno.land/x/diff_parser@v0.2.0/diff.ts:59:20)
    at file:///home/uri/uriva/code-rewrite/src/server.ts:89:16
    at https://deno.land/x/gamla@17.0.0/src/map.ts:14:18
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by uriva** [comment]
nm it happens because github sometimes returns a patch for a single file, which is not a regular git patch
